name: Build & upload specific app to firebase
on:
  workflow_dispatch:
    inputs:
      product:
        type: choice
        required: true
        options:
          - bike
          - car
        description: "Select the product flavor"
      sidePersona:
        type: choice
        required: true
        options:
          - client
          - admin
        description: "Select the side persona flavor"
      release_notes:
        type: string
        required: true
        default: "Manual Debug Build"
        description: "Release notes for the build"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build release
        run: |
          PRODUCT=${{ github.event.inputs.product }}
          SIDEPERSONA=${{ github.event.inputs.sidePersona }}
          VARIANT_NAME="${PRODUCT}${SIDEPERSONA^}Release"
          ./gradlew :app:assemble${VARIANT_NAME}

      - name: Set environment variable for APP_ID
        run: |
          PRODUCT=${{ github.event.inputs.product }}
          SIDEPERSONA=${{ github.event.inputs.sidePersona }}
          APP_ID_KEY="FIREBASE_APP_ID_${PRODUCT^^}_${SIDEPERSONA^^}"
          echo "APP_ID_KEY=$APP_ID_KEY" >> $GITHUB_ENV
        shell: bash

      - name: Set APP_ID from secrets
        run: |
          APP_ID=${{ secrets[env.APP_ID_KEY] }}
          echo "APP_ID=$APP_ID" >> $GITHUB_ENV
        shell: bash

      - name: Verify APP_ID
        run: |
          if [ -z "${{ env.APP_ID }}" ]; then
            echo "APP_ID is not set or invalid"
            exit 1
          fi

      - name: Verify APK exists
        run: |
          PRODUCT=${{ github.event.inputs.product }}
          SIDEPERSONA=${{ github.event.inputs.sidePersona }}
          VARIANT_NAME="${PRODUCT}${SIDEPERSONA^}"
          APK_PATH="app/build/outputs/apk/${VARIANT_NAME}/release/app-${PRODUCT}-${SIDEPERSONA}-release-unsigned.apk"
          echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV
          if [ ! -f $APK_PATH ]; then
            echo "APK not found at $APK_PATH"
            exit 1
          fi

      - name: Print APP_ID and APK_PATH
        run: |
          echo "APP_ID: ${{ env.APP_ID }}"
          echo "APK_PATH: ${{ env.APK_PATH }}"

      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ env.APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: "teste-whitelabelapp"
          file: ${{ env.APK_PATH }}
          releaseNotes: ${{ github.event.inputs.release_notes }}