name: Build & upload All apps to firebase
on:
  workflow_dispatch:
    inputs:
      release_notes:
        type: string
        required: true
        default: "Manual Debug Build"
        description: "Release all apps"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        product: ['bike', 'car']
        sidePersona: ['client', 'admin']

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: build release assembleRelease
        run: ./gradlew :app:assembleRelease{{ matrix.product }}${{ matrix.sidePersona }}Release

      - name: Set environment variable for APP_ID
        run: |
         PRODUCT=${{ matrix.product }}
         SIDEPERSONA=${{ matrix.sidePersona }}
         APP_ID="FIREBASE_APP_ID_${PRODUCT^^}_${SIDEPERSONA^^}"
         echo "APP_ID=$APP_ID" >> $GITHUB_ENV


      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets[env.APP_ID] }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: Teste whiteLabelApp
          file: app/build/outputs/apk/${{ matrix.product }}${{ matrix.sidePersona }}/release/app-${{ matrix.product }}-${{ matrix.sidePersona }}-release-unsigned.apk
          releaseNotes: ${{inputs.release_notes}}