name: Build & upload All apps to firebase
on:
  workflow_dispatch:
    inputs:
      release_notes:
        type: string
        required: true
        default: "Manual Debug Build"
        description: "Release all apps"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        product: ['bike', 'car']
        sidePersona: ['client', 'admin']

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build release
        run: |
          PRODUCT=${{ matrix.product }}
          SIDEPERSONA=${{ matrix.sidePersona }}
          VARIANT_NAME="${PRODUCT}${SIDEPERSONA^}Release"
          ./gradlew :app:assemble${VARIANT_NAME}

      - name: Set environment variable for APP_ID
        run: |
          PRODUCT=${{ matrix.product }}
          SIDEPERSONA=${{ matrix.sidePersona }}
          APP_ID="FIREBASE_APP_ID_${PRODUCT^^}_${SIDEPERSONA^^}"
          echo "APP_ID=$APP_ID" >> $GITHUB_ENV

      - name: Verify APK exists
        run: |
          PRODUCT=${{ matrix.product }}
          SIDEPERSONA=${{ matrix.sidePersona }}
          VARIANT_NAME="${PRODUCT}${SIDEPERSONA^}"
          APK_PATH="app/build/outputs/apk/${VARIANT_NAME}/release/app-${PRODUCT}-${SIDEPERSONA}-release-unsigned.apk"
          echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV
          if [ ! -f $APK_PATH ]; then
            echo "APK not found at $APK_PATH"
            exit 1
          fi

      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: "Teste whiteLabelApp"
          file: ${{ env.APK_PATH }}
          releaseNotes: ${{ inputs.release_notes }}
